/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DecisionEntry = IDL.Record({
  'distanceToObstacle' : IDL.Float64,
  'action' : IDL.Text,
  'speed' : IDL.Float64,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDecisionLog' : IDL.Func([], [IDL.Vec(DecisionEntry)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'slowDownCount' : IDL.Nat,
          'totalDecisions' : IDL.Nat,
          'stopCount' : IDL.Nat,
          'changeLaneCount' : IDL.Nat,
          'goCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'makeDecision' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text, IDL.Bool],
      [IDL.Record({ 'action' : IDL.Text, 'reason' : IDL.Text })],
      [],
    ),
  'resetLog' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DecisionEntry = IDL.Record({
    'distanceToObstacle' : IDL.Float64,
    'action' : IDL.Text,
    'speed' : IDL.Float64,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'getDecisionLog' : IDL.Func([], [IDL.Vec(DecisionEntry)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'slowDownCount' : IDL.Nat,
            'totalDecisions' : IDL.Nat,
            'stopCount' : IDL.Nat,
            'changeLaneCount' : IDL.Nat,
            'goCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'makeDecision' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text, IDL.Bool],
        [IDL.Record({ 'action' : IDL.Text, 'reason' : IDL.Text })],
        [],
      ),
    'resetLog' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };